apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`whoami.traefik.me`)
    services:
    - name: whoami
      port: 80
  tls:
    secretName: traefik-tls-cert
    #store:
    #  name: default